const MODULE = `awesomeLedger/user/`;

const actionTypes = {
  LOGIN_REQUEST: `${MODULE}LOGIN_REQUEST`,
  LOGIN_SUCCESS: `${MODULE}LOGIN_SUCCESS`,
  LOGIN_FAIL: `${MODULE}LOGIN_FAIL`,
  LOGOUT_REQUEST: `${MODULE}LOGOUT_REQUEST`,
  LOGOUT_FAIL: `${MODULE}LOGOUT_REQUEST`,
  LOGOUT_SUCCESS: `${MODULE}LOGOUT_SUCCESS`,
  REGISTER_REQUEST: `${MODULE}REGISTER_REQUEST`,
  REGISTER_FAIL: `${MODULE}REGISTER_FAIL`,
  REGISTER_SUCCESS: `${MODULE}REGISTER_SUCCESS`,
  CLEAR: `${MODULE}CLEAR`,
  RESET: `${MODULE}RESET`
};

export default actionTypes;
